# Generated by Django 4.1 on 2022-11-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_marks_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='regno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marks',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mregno_Student_set', to='newapp.admission'),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regno_Student_set', to='newapp.admission'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
