# Generated by Django 4.1 on 2022-11-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regno_Student_set', to='newapp.student'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='sname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sname_Student_set', to='newapp.student'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_regno_Student_set', to='newapp.student'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_Marks_set', to='newapp.marks'),
        ),
    ]
