# Generated by Django 4.1 on 2022-11-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_marks_regno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='user',
        ),
        migrations.AlterField(
            model_name='admission',
            name='sname',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
