# Generated by Django 4.1 on 2022-10-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
