# Generated by Django 4.1 on 2022-11-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_delete_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='sahil@gmail.com', max_length=254),
        ),
    ]
