# Generated by Django 4.1 on 2022-11-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_courses_fees_delete_company_student_fees_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='country',
        ),
        migrations.AddField(
            model_name='courses',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.city'),
            preserve_default=False,
        ),
    ]
