# Generated by Django 4.1 on 2022-11-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_remove_courses_country_courses_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='amount',
            new_name='balance_amount',
        ),
        migrations.AddField(
            model_name='fees',
            name='total_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
