# Generated by Django 4.1 on 2022-11-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_rename_amount_fees_balance_amount_fees_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
