# Generated by Django 4.1 on 2022-11-18 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70)),
                ('regno', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksregno', to='newapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feedbacks', models.TextField()),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedbackregno', to='newapp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedbacksubject', to='newapp.marks')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('doa', models.DateField()),
                ('semester', models.PositiveIntegerField()),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissionregno', to='newapp.student')),
                ('sname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissionsname', to='newapp.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissionuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
