# Generated by Django 4.1 on 2022-11-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_admission_regno_alter_admission_sname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mregno_Student_set', to='newapp.student'),
        ),
    ]
