# Generated by Django 4.1 on 2022-11-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_admission_user_alter_admission_sname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
