# Generated by Django 4.1 on 2022-12-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
